config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats, only: %i[index show new create ] do
    resources :bookings, only: %i[create]

  end
  resources :bookings, only: %i[index show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flat, only: [:create]
  def index
    @user = current_user
    # @bookings = Booking.all
    @bookings = current_user.bookings
    @flats = Flat.all
  end

  def show
    # bookings/:id
    set_booking
    @flats = Flat.all
  end

  def create
    # flats/:flat_id/bookings
    @user = current_user
    @booking = Booking.new(strong_params)
    @booking.user = @user
    @booking.flat = @flat
    @booking.save
    redirect_to bookings_path
    # redirect_to booking_path(@booking)
  end

  private

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def strong_params
    params.require(:booking).permit(:user_id, :flat_id, :confirm, :start_time, :end_time)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
    user
  end

  def new
    @flat = Flat.new
  end

  def create
    user
    @flat = Flat.new(strong_params)
    @flat.user = @user
    user.owner = true
    @flat.save
    redirect_to flats_path # index
    # redirect_to flat_path(@flat) # show
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
    user
  end

  private

  def user
    @user = current_user
  end

  def strong_params
    params.require(:flat).permit(:user_id, :title, :city, :price, :address, :room_type, :total_occupancy, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container pt-3">
  <h1>Bookings list</h1>
  <br>
  <% @bookings.each do |booking| %>
    <%= booking.flat.title %>
    <br>
    <%= booking.flat.address %>
    <br>
    <%= booking.flat.city %>
    <br>
    <%= booking.start_time.strftime(' %a, %d %B, %Y, %H:%M %P') %>
    <br>
    <%= booking.end_time.strftime(' %a, %d %B, %Y, %H:%M %P') %>
    <br>
    <%= booking.flat.total_occupancy %>
    <br>
    <%= booking.user.email %>
    <hr>
    <%= link_to "visit", flat_path(booking.flat)  %><br>
    <% link_to "info", booking_path(booking)%><br>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="map" style="background-image: url('<%= %>')"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @booking.flat.address%></h1>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <%= @booking.flat.total_occupancy %> Guests
          </div>
          <div class="flex ms-3">
            <%= @booking.flat.price%>€
            <%= @booking.status%>
          </div>
        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-text" id="start-date-label">From:</span>
            <input type="text" class="form-control" aria-label="start-date" aria-describedby="start-date-label">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-text" id="end-date-label">To:</span>
            <input type="text" class="form-control"  aria-label="end-date" aria-describedby="start-date-label">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>

      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div id="bold" class="container">
  <% if @user.owner == false %>
    <div class="card-group">
      <div class="griddy" id= "line">
        <% @flats.each do |list| %>
          <div class="card">
            <%= cl_image_tag list.photo.key, class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><%= list.title %></h5>
              <p class="card-text"><%= list.city %></p>
              <p class="card-text"><%= list.address  %>.</p>
              <p class="card-textp">$<%= list.price %>/ Day</p>
              <p class="card-textt"><%= list.total_occupancy  %>&nbsp;<i class="fa-solid fa-person"></i></p>
            </div>
            <div class="card-footer">
              <%= link_to "View", flat_path(list), class: "card-btn"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h3 class="mt-3">Add a flat </h3>
  <%= simple_form_for(@flat) do |f| %>
  <%= f.input :title %>
  <%= f.input :address %>
  <%= f.input :price %>
  <%= f.input :room_type, as: :select, collection: [['Single Room', 'Single Room'], ['Double Room', 'Double Room'], ['Family Room', 'Family Room'], ['Others', 'Others']] %>
  <%= f.input :total_occupancy, as: :select, collection: [['1 Guest', '1'], ['2 Guest', '2'], ['3 Guest', '3'], ['4 or more guest', '4+']] %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<%# <%= stylesheet_link_tag('show') %>
<div id="mt-3" class="container p-auto">
  <div class="row mx-auto mt-3">
      <div id="whitey" class="col-md-7 border-left p-3">
        <%= cl_image_tag @flat.photo.key, class: "m-3", height: 300, width: 400, crop: :fill %>
        <div class="alert-success" role="alert"></div>
        <div id="alllign">
          <h5 class="m-auto alert-heading"> <%= @flat.title %></h5><br>
          <h5 class="m-auto"><%= @flat.address %></h5>
          <h5 class="m-auto"> £ <%= @flat.price %></h5>
          <%# <h5 class="m-auto">Max Guests: <%= @flat.total_occuh5ancy %>
          <h5 class="mb-3"><%= @flat.room_type.capitalize %></h5><br>
          <h6> Perfect place to get some space from your partner.</h6>
        </div>
      </div>
      <div id="checky" class="col-md-3 justify-content-end bg-black text-white bg-opacity-75 m-auto pt-3">
        <%= simple_form_for [@flat, @booking], data: { controller: 'flatpickr'} do |f| %>
          <% if @user.owner == false %>
          <%= f.input :start_time, label: 'Check-in', as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
          <%= f.input :end_time, label: 'Check-out', as: :string, input_html: { data: { flatpickr_target: "endTime" }, id: 'end_time' } %>
          <%= f.input :status, label: 'Guests', as: :select, collection: [['Send Request', '0']] %>
          <div class="d-grid">
            <%= f.submit class: "btn btn-primary mx-auto pb-2" %>
          </div>

          <% else %>
          <%= f.input :status, label: 'Approval', as: :radio_buttons, collection: [['Reject', '1'], ['Confrim', '2']] %>
          <%= f.submit class: "btn btn-primary mx-auto pb-2" %>
          <% end  %>
          <% end %>
        </div>
  </div>
  <div id="box" class="col-md-5 border-left">
    <img src="https://a0.muscache.com/im/pictures/54e427bb-9cb7-4a81-94cf-78f19156faad.jpg" width="215" height="50">
    <span class="caption">Every booking includes free protection from Host cancellations, listing inaccuracies, and other issues like trouble checking in.</span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
    
      <%= render "shared/navbar" %>
      <%= yield %>
      <%= render "shared/flashes" %>
      <%= render "shared/footer" %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<body>
  <div class="container">
    <div id="carouselExampleDark" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="<%= image_path 'flats_7.webp'%>" class="d-block w-100" alt="">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="<%= image_path 'flats_5.jpg'%>" class="d-block w-100 h-50" alt="Flat1">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
      <div class="carousel-item">
        <img src="<%= image_path 'flats_6.jpg' %>"" class="d-block w-100 h-50" alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
    </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" color="white" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" color="white" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
  </div>
  <div class="container1">
    <div class="text-center">
      <%= link_to "See Flats to rent", flats_path, class: "btn w-50"%>
      <%= link_to "Add your flat to rent", new_flat_path, class: "btn w-50"%>
    </div>
  </div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer>
    <ul>
      <%# <div class="footer-left"> %>
        <li class= "footer-text">©2022 Airbnb, Inc.</li>
        <a href="#"><li class="footer-text">Privacy</li></a>
        <a href="#"><li class="footer-text">Terms</li></a>
        <a href=""><li class="footer-text">Sitemap</li></a>
        <a href="#"><li class="footer-text">Destinations</li></a>
      <%# </div>
      <div class ="footer-right" > %>
        <a href=""><li class="footer-text"> <i class="fa-solid fa-globe"></i> English(AU) </li></a>
        <a href=""><li class="footer-text">$AUD</li></a>
        <a href=""><li class="footer-text">Support and Resources</li></a>
      <%# </div> %>
    </ul>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>

      <div id="logo" >
         <h4>&nbsp;<i class="fa-brands fa-airbnb size"></i></h4>
      </div>

    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li>
            <form class="search-box d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            </form>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Flats", flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">

          <%# <i class="fa-solid fa-house"> %>
            <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU0iftAO8imgKArtQvaaLu1gL0NtbaL4St2dzgXTg&s", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to "", "#", class: "dropdown-item" %>
              <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>

              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>